site_name: data-gradients
docs_dir: .
nav:
- Welcome:
  - Intro: .README.md
  - Feature Description: ./documentation/feature_description.md
  - Feature Configuration: ./documentation/feature_configuration.md
