common:
  - _target_: data_gradients.feature_extractors.common.count_images_labels.NumberOfImagesLabels
  - _target_: data_gradients.feature_extractors.common.image_resolutions.ImagesResolutions
  - _target_: data_gradients.feature_extractors.common.image_aspect_ratios.ImagesAspectRatios
  - _target_: data_gradients.feature_extractors.common.average_brightness.AverageBrightness
  - _target_: data_gradients.feature_extractors.common.mean_std.MeanAndSTD
