report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Object Detection Features
    features:
#      - DetectionSampleVisualization:
#          n_rows: 3
#          n_cols: 4
#          stack_splits_vertically: True
      - DetectionClassHeatmap:
          n_rows: 6
          n_cols: 2
          heatmap_shape: [200, 200]
      - DetectionBoundingBoxArea:
          topk: 30
          prioritization_mode: train_val_diff
      - DetectionBoundingBoxPerImageCount
      - DetectionBoundingBoxSize
      - DetectionClassFrequency:
          topk: 30
          prioritization_mode: train_val_diff
      - DetectionClassesPerImageCount:
          topk: 30
          prioritization_mode: train_val_diff
      - DetectionBoundingBoxIoU:
          num_bins: 10
          class_agnostic: true
      - DetectionResizeImpact:
          resizing_sizes:
            - [64, 64]
            - [96, 96]
            - [128, 128]
            - [160, 160]
            - [192, 192]
            - [224, 224]
            - [256, 256]
            - [320, 320]
            - [384, 384]
            - [448, 448]
            - [512, 512]
            - [640, 640]
            - [768, 768]
            - [896, 896]
            - [1024, 1024]
          area_thresholds: [1,4,9,16,64]
