report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Object Detection Features
    features:
      - DetectionSampleVisualization
      - DetectionClassHeatmap
      - DetectionBoundingBoxArea:
          top_k: 30
      - DetectionBoundingBoxPerImageCount
      - DetectionBoundingBoxSize
      - DetectionClassesCount
      - DetectionClassesPerImageCount:
          top_k: 30
