report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Object Detection Features
    features:
      - DetectionSampleVisualization
      - DetectionClassHeatmap
      - DetectionBoundingBoxArea
      - DetectionBoundingBoxPerImageCount
      - DetectionBoundingBoxSize
      - DetectionClassesCount
      - DetectionClassesPerImageCount
