report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Object Detection Features
    features:
      - DetectionSampleVisualization:
          n_samples_per_split: 8
          n_cols_per_split: 2
          stack_splits_vertically: True
      - DetectionClassHeatmap:
          n_classes_to_show: 12
          n_cols: 2
          heatmap_dim: [200, 200]
      - DetectionBoundingBoxArea
      - DetectionBoundingBoxPerImageCount
      - DetectionBoundingBoxSize
      - DetectionClassesCount
      - DetectionClassesPerImageCount
