report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Segmentation Features
    features:
      - SegmentationSampleVisualization:
          n_samples_per_split: 9
          n_cols_per_split: 3
          stack_splits_vertically: True
          stack_mask_vertically: True
      - SegmentationClassHeatmap:
          n_classes_to_show: 12
          n_cols: 2
          heatmap_dim: [200, 200]
      - SegmentationClassesCount
      - SegmentationClassesPerImageCount
      - SegmentationComponentsPerImageCount
      - SegmentationBoundingBoxResolution
      - SegmentationBoundingBoxArea
      - SegmentationComponentsConvexity
      - SegmentationComponentsErosion
