report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Segmentation Features
    features:
      - SegmentationSampleVisualization:
          n_rows: 3
          n_cols: 3
          stack_splits_vertically: True
          stack_mask_vertically: True
      - SegmentationClassHeatmap:
          n_rows: 6
          n_cols: 2
          heatmap_shape: [200, 200]
      - SegmentationClassFrequency
      - SegmentationClassesPerImageCount
      - SegmentationComponentsPerImageCount
      - SegmentationBoundingBoxResolution
      - SegmentationBoundingBoxArea
      - SegmentationComponentsConvexity
      - SegmentationComponentsErosion
