report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Segmentation Features
    features:
      - SegmentationSampleVisualization
      - SegmentationClassHeatmap
      - SegmentationClassesCount
      - SegmentationClassesPerImageCount:
          top_k: 30
      - SegmentationComponentsPerImageCount
      - SegmentationBoundingBoxResolution
      - SegmentationBoundingBoxArea:
          top_k: 30
      - SegmentationComponentsConvexity
      - SegmentationComponentsErosion
