report_sections:
  - name: Image Features
    features:
      - SummaryStats
      - ImagesResolution
      - ImageColorDistribution
      - ImagesAverageBrightness
  - name: Segmentation Features
    features:
      - SegmentationSampleVisualization
      - SegmentationClassHeatmap
      - SegmentationClassesCount
      - SegmentationClassesPerImageCount
      - SegmentationComponentsPerImageCount
      - SegmentationBoundingBoxResolution
      - SegmentationBoundingBoxArea
      - SegmentationComponentsConvexity
      - SegmentationComponentsErosion
