number_of_classes:
ignore_labels:

defaults:
  - common: common
  - _self_

feature_extractors:
  - SegmentationClassesCount
  - SegmentationClassesPerImageCount
  - SegmentationComponentsPerImageCount
  - SegmentationBoundingBoxResolution
  - SegmentationBoundingBoxArea
  - SegmentationComponentsConvexity
  - SegmentationComponentsErosion
  - SegmentationComponentCenterOfMass


_convert_: all
