number_of_classes:
ignore_labels:

defaults:
  - common: common
  - _self_

feature_extractors:
  - SegmentationBoundingBoxArea
  - SegmentationBoundingBoxResolution
  - SegmentationClassesCount
  - SegmentationClassesPerImageCount
  - SegmentationComponentCenterOfMass
  - SegmentationComponentsConvexity
  - SegmentationComponentsErosion
  - SegmentationComponentsPerImageCount


_convert_: all
