number_of_classes:
ignore_labels:

defaults:
  - common: common
  - _self_

feature_extractors:
  - _target_: data_gradients.feature_extractors.segmentation.classes_distribution.GetClassDistribution
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.classes_number_of_pixels.PixelsPerClass
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.classes_appearances_in_images.AppearancesInImages
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.bounding_boxes_area.ComponentsSizeDistribution
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.components_center_of_mass.ComponentsCenterOfMass
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.labels_aspect_ratios.LabelsAspectRatios
  - _target_: data_gradients.feature_extractors.segmentation.labels_resolutions.LabelsResolutions
  - _target_: data_gradients.feature_extractors.segmentation.count_num_components.CountNumComponents
  - _target_: data_gradients.feature_extractors.segmentation.bounding_boxes_width_height.WidthHeight
  - _target_: data_gradients.feature_extractors.segmentation.components_convexity.ComponentsConvexity
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.components_erosion.ErosionTest
    n_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: data_gradients.feature_extractors.segmentation.count_small_components.CountSmallComponents
    minimum_percent_of_an_image: 0.0005
