common:
#  - _target_: src.feature_extractors.common.count_images_labels.NumberOfImagesLabels
#  - _target_: src.feature_extractors.common.image_resolutions.ImagesResolutions
#  - _target_: src.feature_extractors.common.image_aspect_ratios.ImagesAspectRatios
#  - _target_: src.feature_extractors.common.average_brightness.AverageBrightness
#   - _target_: src.feature_extractors.segmentation.bounding_boxes_area.ComponentsSizeDistribution
#     num_classes: ${number_of_classes}
#     ignore_labels: ${ignore_labels}
