number_of_classes:
ignore_labels:

defaults:
  - common

semantic_segmentation:
  - _target_: src.feature_extractors.segmentation.get_class_distribution.GetClassDistribution
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.pixels_per_class.PixelsPerClass
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.appearances_in_images.AppearancesInImages
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.objects_size.ObjectSizeDistribution
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.objects_center_of_mass.ObjectsCenterOfMass
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.labels_aspect_ratios
  - _target_: src.feature_extractors.segmentation.labels_resolutions
  - _target_: src.feature_extractors.segmentation.count_num_objects.CountNumObjects
  - _target_: src.feature_extractors.segmentation.width_height.WidthHeight
#  - _target_: feature_extractors.segmentation.count_small_objects.SegmentationCountSmallObjects
#    percent_of_an_image: 1

