number_of_classes:
ignore_labels:

defaults:
  - common

semantic_segmentation:
  - _target_: src.feature_extractors.segmentation.classes_distribution.GetClassDistribution
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.classes_number_of_pixels.PixelsPerClass
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.classes_appearances_in_images.AppearancesInImages
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.bounding_boxes_area.ObjectSizeDistribution
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.components_center_of_mass.ObjectsCenterOfMass
    num_classes: ${number_of_classes}
    ignore_labels: ${ignore_labels}
  - _target_: src.feature_extractors.segmentation.labels_aspect_ratios.LabelsAspectRatios
  - _target_: src.feature_extractors.segmentation.labels_resolutions.LabelsResolutions
  - _target_: src.feature_extractors.segmentation.count_num_components.CountNumObjects
  - _target_: src.feature_extractors.segmentation.bounding_boxes_width_height.WidthHeight
#  - _target_: src.feature_extractors.segmentation.components_convexity.ComponentsConvexity
#  - _target_: src.feature_extractors.segmentation.labels_erosion_test.ErosionTest
#  - _target_: feature_extractors.segmentation.count_small_objects.SegmentationCountSmallObjects
#    percent_of_an_image: 1

